Resources:
  MyFirstS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "agt1234567"
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03972092c42e8c0ca
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20


